const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
const ENCREASE_PRODUCT = "ENCREASE_PRODUCT";
const DECREASE_PRODUCT = "DECREASE_PRODUCT";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const ALL_PRODUCTS_SUCESS = "ALL_PRODUCTS_SUCESS";
const PRODUCTS_HAS_ERRORED = "PRODUCTS_HAS_ERRORED";
const PRODUCTS_IS_LOADING = "PRODUCTS_IS_LOADING";
const PRODUCT_UPDATE = "PRODUCT_UPDATE";

export {
    ADD_PRODUCT_TO_CART,
    ENCREASE_PRODUCT,
    DECREASE_PRODUCT,
    DELETE_PRODUCT,
    ALL_PRODUCTS_SUCESS,
    PRODUCTS_HAS_ERRORED,
    PRODUCTS_IS_LOADING,
    PRODUCT_UPDATE
}